#!/bin/bash
#     _               ___
#    / \   _ __  _ __|_ _|_ __ ___   __ _  __ _  ___
#   / _ \ | '_ \| '_ \| || '_ ` _ \ / _` |/ _` |/ _ \
#  / ___ \| |_) | |_) | || | | | | | (_| | (_| |  __/
# /_/   \_\ .__/| .__/___|_| |_| |_|\__,_|\__, |\___|
#         |_|   |_|                       |___/
#  ___       _                       _
# |_ _|_ __ | |_ ___  __ _ _ __ __ _| |_ ___  _ __
#  | || '_ \| __/ _ \/ _` | '__/ _` | __/ _ \| '__|
#  | || | | | ||  __/ (_| | | | (_| | || (_) | |
# |___|_| |_|\__\___|\__, |_|  \__,_|\__\___/|_|
#                    |___/
#
# Author Andrianos Papamarkou
# Email: apapamarkou@yahoo.com
#
# This script will install the appimage-integrator on your system.

# Define the repository URL and the directory name
REPO_URL="https://github.com/apapamarkou/appimage-integrator.git"
REPO_DIR="appimage-integrator"

# Clone the repository
echo "Cloning the repository..."
git clone "$REPO_URL"

# Change to the repository directory
cd "$REPO_DIR" || { echo "Failed to change directory to $REPO_DIR"; exit 1; }

# Make all files executable
echo "Making all files executable..."
chmod a+x *

# Run the install script
echo "Running the install script..."
./install.sh

# Return to the previous directory
cd ..

# Remove the cloned repository directory
echo "Cleaning up..."
rm -rf "$REPO_DIR"

echo "Thank you for running appimage-integrator."
